// <auto-generated />
namespace DOAN_COSO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LamLaiDBdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LamLaiDBdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202204170857029_LamLaiDBdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
